services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      env_file:
        - ./.env.docker
      networks:
        - univer_net
      depends_on:
        - postgres
        - minio
        - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
      
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - univer_net

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: 'user'
      MINIO_ROOT_PASSWORD: 'password'
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server  --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - univer_net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  univer_net:
    name: univer_net

volumes:
  minio_data:
    name: minio_data
  redis_data:
    name: redis_data

