// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgrepository

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	Uuid      uuid.UUID `json:"uuid"`
	UserUuid  uuid.UUID `json:"user_uuid"`
	Name      string    `json:"name"`
	Size      int64     `json:"size"`
	IsCrypt   bool      `json:"is_crypt"`
	CreatedAt time.Time `json:"created_at"`
}

type FileCryptoKey struct {
	FileUuid     uuid.UUID `json:"file_uuid"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	SymmetricKey string    `json:"symmetric_key"`
}

type User struct {
	Uuid         uuid.UUID `json:"uuid"`
	PasswordHash string    `json:"password_hash"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PublicKey    []byte    `json:"public_key"`
}
